/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package totpdemo;

import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class FromTOTP extends javax.swing.JFrame {
    private String secretKey; // Secret Key giả lập
    private int timeStep = 30; // Thời gian TOTP
    private int counter = 30;
   
    /**
     * Creates new form FromTOTP
     */
    public FromTOTP(String secretKey) {
         this.secretKey = secretKey;
         initComponents();
          lblTOTP.setText("Mã OTP: " + generateTOTP());
         startCountdown();
    }
    private String generateTOTP() {
        try {
            return Generator.generateTOTP(secretKey, timeStep);
        } catch (Exception ex) {
            System.err.println("Lỗi khi tạo TOTP: " + ex.getMessage());
            return "Lỗi khi tạo OTP";
        }
    }
    private void startCountdown() {
        counter = 30; // Khởi tạo giá trị đếm ngược
        Timer timer = new Timer(1000, (e) -> { // Timer chạy mỗi giây
            if (counter == 0) {
                counter = 30; // Reset lại bộ đếm
                lblTOTP.setText("Mã OTP: " + generateTOTP()); // Hiển thị TOTP mới
            }
            lbltimer.setText("Thời gian còn lại: " + counter + " giây"); // Hiển thị thời gian
            counter--; // Giảm bộ đếm
        });
        timer.setRepeats(true); // Lặp lại Timer
        timer.start(); // Bắt đầu Timer
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsecretkey = new javax.swing.JLabel();
        txtsecretkey = new javax.swing.JTextField();
        txtTOTP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblresult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbltimer = new javax.swing.JLabel();
        lblTOTP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblsecretkey.setText("Secret Key");

        txtsecretkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsecretkeyActionPerformed(evt);
            }
        });

        jButton1.setText("Xác Minh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblresult.setText("Thông báo");

        jLabel1.setText("Nhập TOTP");

        lbltimer.setText("Thời gian đếm ngược");

        lblTOTP.setText("TOTP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsecretkey, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsecretkey, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jButton1))
                            .addComponent(lblresult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltimer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsecretkey)
                    .addComponent(txtsecretkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(21, 21, 21)
                        .addComponent(lblresult))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTOTP)
                        .addGap(49, 49, 49)
                        .addComponent(lbltimer)))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String userInput = txtTOTP.getText();
    try {
        String currentOTP = Generator.generateTOTP(secretKey, 30); // Tạo OTP
        if (userInput.equals(currentOTP)) {
            JOptionPane.showMessageDialog(this,"Bảo mật 2 lớp thành công!");
            lblresult.setText("OTP chính xác!");
            Frm_TrangChu trangChu = new Frm_TrangChu();
            trangChu.setVisible(true);
            this.dispose();
        } else {
            lblresult.setText("OTP không chính xác!");
        }
    } catch (Exception ex) {
        lblresult.setText("Lỗi khi tạo OTP: " + ex.getMessage());
        System.err.println("Lỗi khi tạo OTP: " + ex.getMessage()); // In lỗi ra console
        

    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsecretkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsecretkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsecretkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromTOTP("JBSWY3DPEHPK3PXP").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTOTP;
    private javax.swing.JLabel lblresult;
    private javax.swing.JLabel lblsecretkey;
    private javax.swing.JLabel lbltimer;
    private javax.swing.JTextField txtTOTP;
    private javax.swing.JTextField txtsecretkey;
    // End of variables declaration//GEN-END:variables
}
